---
name: Tests

on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ 
          ubuntu-latest
#          ,windows-latest 
        ]
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          
      - name: Start containers
        run: docker-compose up -d
      - name: Test
        run: dotnet test
        